apiVersion: apps/v1
kind: Deployment
metadata:
  name: videos-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hipstergram-videos
  template:
    metadata:
      labels:
        app: hipstergram-videos
    spec:
      containers:
        - image: klemenstanic/video-api:latest
          name: video-api 
          env:
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: db-connection-url-videos-api
            - name: LOGS_URI 
              valueFrom:
                secretKeyRef:
                  name: log-connection 
                  key: log-connection-url 
            - name: LOGS_PORT
              valueFrom:
                secretKeyRef:
                  name: log-connection
                  key: log-connection-port
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: videos-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: hipstergram-videos 
